### ISSUE TITLE
Не играет песни

### ISSUE THREAD

**Issue by gudoalexander** [scorpp/db-vk#30]
Добавленные песни в плейлист не играет. Компилил на kubuntu 14.04 x86_64 c  libcurl gnutls.
Deadbeef 0.6.1
Типа начинает буферизироваться и перескакивает на следующие треки

**Comment by dmgl** [comment]
Здравствуйте, не помогло. 

В настройках VK снял галочку "всегда использовать безопасное соединение", но все равно после добавления трека из поиска возспроизведение не работает:

В консоль вываливается:

```
= Getting my music, uid=169399
Requesting URL https://api.vk.com/method/audio.get?access_token=xxx
Requesting URL https://api.vk.com/method/audio.getById?access_token=xxx&audios=169399_369999306
vk_vfs_store_track: http://cs6-9v4.vk-cdn.net/p4/f4d3b2c1a605a4.mp3?extra=DNpVpqhyBtmPblVDdHhhA8_lGLE-6v9DOwbGgRI5Ubp3O0qmfXxYqM7wsIHC-Gbaz1af4EVMGb4AV-ghKNoANE1f8EGP, index=0
```

Deadbeef ставил из репозитория:

```
/etc/apt/sources.list.d/starws-box-deadbeef-player-trusty.list
deb http://ppa.launchpad.net/starws-box/deadbeef-player/ubuntu trusty main
```

Версия:

```
Package: deadbeef
Priority: optional
Section: sound
Installed-Size: 8091
Maintainer: starws <starws.box@gmail.com>
Architecture: amd64
Version: 0.6.2.2-1~trusty~ppa1
```

В ~/.local/lib/deadbeef положил
```
vkontakte_gtk2.so*
vkontakte_gtk3.so*
```
которые собрал без проблем.

Версия http://sourceforge.net/projects/deadbeef/files/deadbeef-static_0.6.2-2_x86_64.tar.bz2/download заработала. В чем причина не пойму...

**Comment by scorpp** [comment]
видимо, в starws-box PPA плеер собран без чего-то нужного.

я бы попробовал
а) посмотреть в плагинах deadbeef"а, что есть cURL плагин
б) взять прямую ссылку на mp3 из вывода в терминале, скачать оттуда mp3 wget"ом, подсунуть deadbeef"у - проверить, что сама mp3"шка не битая и вообще
в) в deadbeef"е добавить этот же URL через File - Add location. скорее всего играть будет, но это только лишь докажет, что VK plugin здесь ни при чём.

**Comment by Mayurifag** [comment]
Неужели никто не смог решить до сих пор эту проблему без убирания злополучной галочки? Если есть решения — подскажите. Я на арчике сижу.

**Comment by medvedar** [comment]
Сам deadbeef не умеет https: linux.org.ru/forum/multimedia/9652929?cid=10535303
