### ISSUE TITLE
Более подробная инструкция по компиляции

### ISSUE THREAD

**Issue by GRbit** [scorpp/db-vk#31]
С одной стороны компилируют не дураки конечно, но мне бы очень пригодился список конкретных пакетов необходимых для компиляции. В общем, по-моему вот такая строчка в Reamde была бы удобна
sudo apt-get install libgtk2.0-dev libgtk-3-dev libcurl4-gnutls-dev libjson-glib-dev cmake
Может добавить?)

**Comment by scorpp** [comment]
добавил
