### ISSUE TITLE
Arch: PKGBUILD завязан на GTK3

### ISSUE THREAD

**Issue by squizduos** [scorpp/db-vk#33]
Не думаю, что это очень большой баг, но арчевский PKGBUILD завязан на GTK3, и плагин по умолчанию собирается для GTK3. Если Deadbeef собран с GTK2 - плагин не запустится без всяких предупреждений. Возможно, есть смысл сделать два отдельных пакета, или дать пользователю выбор, для какого GTK собирать пакет.

**Comment by scorpp** [comment]
https://aur.archlinux.org/packages/deadbeef-plugin-vk-gtk2/
