### ISSUE TITLE
Добавить возможность слушать свои рекомендации

### ISSUE THREAD

**Issue by medvedar** [scorpp/db-vk#34]
https://vk.com/dev/audio.getRecommendations
Метод есть. Было бы здорово иметь такой функционал.

**Comment by scorpp** [comment]
рекомендации для пользователя? для трека будет сложно УЙ наворотить, я думаю

**Comment by medvedar** [comment]
Да. Рядом с кнопкой "My music" сделать "My recommendation" .

**Comment by scorpp** [comment]
ну тогда жду пул риквестов :)

2016-04-05 21:11 GMT+03:00 Max Medar <notifications@github.com>:
